"""empty message

Revision ID: 8e30ff2b803d
Revises: 2b740ecd7aa6
Create Date: 2018-12-22 20:08:49.986238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30ff2b803d'
down_revision = '2b740ecd7aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regex_name'), 'regex', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regex_name'), table_name='regex')
    op.drop_table('regex')
    # ### end Alembic commands ###
